### ISSUE TITLE
Unknow word when using postcss mixin plugin with postcss-env-function

### ISSUE THREAD

**Issue by leozero** [csstools/postcss-env-function#12]
Hello,

I have an issue when I'm using **postcss-env-function** with **postcss-mixin**

In my **postcss.config.js** I have : 
` require('postcss-import'),
      require('tailwindcss'),
      require('autoprefixer'),
      require('postcss-mixins'),
      require('cssnano'),
      require('postcss-nested'),
      postcssEnvFunction({
        importFrom: './css-env.js',
      }),`

And I also have a mixin file with for example : 
`@define-mixin lines $lines {
  display: -webkit-box;
  -webkit-line-clamp: $lines;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
`

And when I run postcss I have this error : 
`CssSyntaxError: postcss-env-fn: <css input>:1:7: Unknown word

> 1 | lines $lines
    |       ^
`

When I removed postcss-env-function I don't have this error.

Any idea how I can resolve this issue ? 

Thanks !

**Comment by Antonio-Laguna** [comment]
@leozero could you try this with latest versions?

**Comment by romainmenke** [comment]
Hi @leozero we are archiving this repo as this plugin has moved to [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins)

We hope this issue has already be resolved in the latest patches.
If it's not, can you [open a new issue here](https://github.com/csstools/postcss-plugins/issues/new/choose)?
